name: test_code_magic
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  flutter_riverpod: ^2.5.1
  riverpod_annotation: 2.3.5
  http_mock_adapter: ^0.6.1
  dio: ^5.7.0
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  json_serializable: ^6.8.0
  custom_refresh_indicator: ^4.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  custom_lint: 0.6.4
  flutter_lints: ^4.0.0
  riverpod_generator: 2.4.0
  riverpod_lint: 2.3.10
  mocktail: ^1.0.3
  build_runner: ^2.4.10

flutter:
  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
